## Roughly based on https://github.com/jda/docker-moodle/
FROM code4sa/moodle-deps-base:latest
MAINTAINER Code For South Africa <info@code4sa.org>

ADD ./foreground.sh /etc/apache2/foreground.sh

RUN rm -f /var/www/html/index.html && \
    cd /tmp && \
    wget https://download.moodle.org/download.php/direct/stable32/moodle-latest-32.tgz && \
    tar -xf moodle-latest-32.tgz && \
    mv /tmp/moodle/* /var/www/html/ && \
    chown -R www-data:www-data /var/www/html && \
    chmod +x /etc/apache2/foreground.sh
